-- 用户留言表：存储 Contact Us 页面 "Send Us a Message" 表单提交的留言
-- 在 Supabase SQL Editor 中运行

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

drop policy if exists "messages insert" on public.messages;
create policy "messages insert" on public.messages
  for insert to anon, authenticated with check (true);

drop policy if exists "messages select" on public.messages;
create policy "messages select" on public.messages
  for select to anon, authenticated using (true);

drop policy if exists "messages delete" on public.messages;
create policy "messages delete" on public.messages
  for delete to anon, authenticated using (true);
